name: pages-with-recursive-sitemap
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # OPTIONAL: also generate per-folder listings (clickable browsing)
      - name: Generate per-directory listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: .

      # SINGLE PAGE: recursive sitemap index
      - name: Generate recursive sitemap index.html
        run: |
          cat > index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Repository sitemap</title>
          <h1>Repository sitemap</h1>
          <ul>
          HTML
          # list everything except the .git, .github/workflows, and the generated artifact dirs
          find . -type d \( -name .git -o -name .github \) -prune -o -print | \
          sed 's|^\./||' | while read p; do
            if [ -z "$p" ]; then continue; fi
            if [ -d "$p" ]; then
              echo "<li><strong><a href=\"$p/\">$p/</a></strong></li>" >> index.html
            else
              echo "<li><a href=\"$p\">$p</a></li>" >> index.html
            fi
          done
          echo "</ul>" >> index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    permissions: { pages: write, id-token: write }
    environment: { name: github-pages, url: ${{ steps.deployment.outputs.page_url }} }
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
