name: sitemap-under-subpath
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Create sitemap folder
      - name: Create sitemap directory
        run: mkdir -p sitemap

      - name: Generate recursive sitemap inside /sitemap
        run: |
          set -euo pipefail
          echo '<!doctype html><meta charset="utf-8"><title>Repository sitemap</title><h1>Repository sitemap</h1><ul>' > sitemap/index.html
          find . -mindepth 1 -not -path "./.git/*" -not -path "./.github/*" -print \
          | sed 's|^\./||' \
          | while read -r p; do
              if [ -d "$p" ]; then
                printf '<li><strong><a href="../%s/">%s/</a></strong></li>\n' "$p" "$p" >> sitemap/index.html
              else
                printf '<li><a href="../%s">%s</a></li>\n' "$p" "$p" >> sitemap/index.html
              fi
            done
          echo '</ul>' >> sitemap/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
